version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
